apiVersion: v1
kind: List
metadata:
  name: analysis
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: analysis
    labels:
      app: analysis
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: analysis
    labels:
      app: analysis
  spec:
    triggers:
      -
        type: ImageChange
    source:
      type: Dockerfile
      dockerfile: |-
        FROM centos:7
        RUN yum install -y nc telnet traceroute
        RUN groupadd -r app -g 1000 && useradd -u 1000 -r -g app -m -d /app -s /sbin/nologin -c "User app" app && chmod 755 /app
        WORKDIR /app
        USER app
        CMD ["/bin/sh"]
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: "centos:7"
    output:
      to:
        kind: ImageStreamTag
        name: "analysis:latest"
