apiVersion: v1
kind: List
metadata:
  name: analysis
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: analysis
    labels:
      app: analysis
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: analysis
    labels:
      app: analysis
  spec:
    triggers:
      -
        type: ImageChange
    source:
      type: Dockerfile
      dockerfile: |-
        FROM gliderlabs/alpine:latest
        RUN apk add --no-cache curl bind-tools apache2-utils mysql-client postgresql-client
        RUN addgroup -S app && adduser -S -g app app
        WORKDIR /app
        USER app
        CMD ["/bin/sh"]
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: "centos:7"
    output:
      to:
        kind: ImageStreamTag
        name: "analysis:latest"
